language: c

before_install:
  - free -m
  - ps -wweo pcpu,pmem,args --sort -pmem
  - ls /etc/init.d
  - apt-get update -qq

install:
  - apt-get install ccache

script:
  - NCORES=$(grep --count processor /proc/cpuinfo); echo $NCORES cores
  - sysctl vm.swappiness
  - sysctl vm.overcommit_memory
  - uname -a
  - mount
  - ulimit -a
  - ccache -s
  - echo ${CCACHE_DIR}

before_deploy:
  - echo "Hello world!" > hello.txt
  
deploy:
  provider: s3
  access_key_id: $S3_BUILD_KEY_ID
  secret_access_key: $S3_BUILD_KEY_SECRET
  bucket: "spacecodesign-dev"
  skip_cleanup: true
  upload-dir: build/sandbox
