language: c

before_install:
  - free -m
  - ps -wweo pcpu,pmem,args --sort -pmem
  - ls /etc/init.d
  - sudo service mysql stop
  - sudo service postgresql stop
  - sudo service couchdb stop
  - sudo service cron stop  
  - sudo service dbus stop
  - sudo service udev stop
  - sudo rm -rf /var/ramfs/mysql
  - sudo rm -rf /var/ramfs/postgresql
  - sudo apt-get -qq update
  
install:
  - sudo apt-get install ash smem

script:
  - NCORES=$(grep --count processor /proc/cpuinfo); echo $NCORES cores
  - free -m
  - ps -wweo pcpu,pmem,args --sort -pmem
  - sudo smem
  - uname -a
  - mount
  - ulimit -a
  - which bash; bash --version
  - which ash; apt-cache policy ash
  - which make; make -v
  - which ld; ld -v
  - which gold; gold -v
  - which i586-mingw32msvc-gcc; i586-mingw32msvc-gcc -v
  - find /usr/lib | grep libmpfr
  - find /usr/lib | grep libgmp
