language: c

before_install:
  - free -m
  - ps -eo pcpu,pmem,args --sort -pmem
  - ls /etc/init.d
  - service mysql stop
  - sudo apt-get update
  
install:
  - sudo apt-get install ash

script:
  - NCORES=$(grep --count processor /proc/cpuinfo); echo $NCORES cores
  - free -m
  - uname -a
  - mount
  - which bash; bash --version
  - which ash; apt-cache policy ash
  - which make; make -v
  - which ld; ld -v
  - which gold; gold -v
  - which i586-mingw32msvc-gcc; i586-mingw32msvc-gcc -v
  - find /usr/lib | grep libmpfr
  - find /usr/lib | grep libgmp
