language: c

before_install:
  - free -m
  - ps -wweo pcpu,pmem,args --sort -pmem
  - ls /etc/init.d

script:
  - NCORES=$(grep --count processor /proc/cpuinfo); echo $NCORES cores
  - sysctl vm.swappiness
  - sysctl vm.overcommit_memory
  - uname -a
  - mount
  - ulimit -a
